### ISSUE TITLE
[bug]: self-hosted planebackend exited with code 1

### ISSUE THREAD

**Issue by geniusshiun** [makeplane/plane#1711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use develop branch start docker-compose up -d by docker-compose.yml with build.

```
planebackend           | Traceback (most recent call last):
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
planebackend           |     return self.cursor.execute(sql, params)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
planebackend           |     raise ex.with_traceback(None)
planebackend           | psycopg.errors.UndefinedColumn: column "cover_image" of relation "users" does not exist
planebackend           | LINE 1: ...r", "email", "first_name", "last_name", "avatar", "cover_ima...
planebackend           |                                                              ^
planebackend           |
planebackend           |
planebackend           | The above exception was the direct cause of the following exception:
planebackend           |
planebackend           |
planebackend           | Traceback (most recent call last):
planebackend           |   File "/code/bin/user_script.py", line 28, in <module>
planebackend           |     populate()
planebackend           |   File "/code/bin/user_script.py", line 19, in populate
planebackend           |     user = User.objects.create(email=default_email, username=uuid.uuid4().hex)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
planebackend           |     return getattr(self.get_queryset(), name)(*args, **kwargs)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
planebackend           |     obj.save(force_insert=True, using=self.db)
planebackend           |   File "/code/plane/db/models/user.py", line 113, in save
planebackend           |     super(User, self).save(*args, **kwargs)
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 76, in save
planebackend           |     super().save(*args, **kwargs)
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
planebackend           |     self.save_base(
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
planebackend           |     updated = self._save_table(
planebackend           |               ^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
planebackend           |     results = self._do_insert(
planebackend           |               ^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
planebackend           |     return manager._insert(
planebackend           |            ^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
planebackend           |     return getattr(self.get_queryset(), name)(*args, **kwargs)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
planebackend           |     return query.get_compiler(using=using).execute_sql(returning_fields)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
planebackend           |     cursor.execute(sql, params)
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
planebackend           |     return self._execute_with_wrappers(
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
planebackend           |     return executor(sql, params, many, context)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
planebackend           |     with self.db.wrap_database_errors:
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
planebackend           |     raise dj_exc_value.with_traceback(traceback) from exc_value
planebackend           |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
planebackend           |     return self.cursor.execute(sql, params)
planebackend           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
planebackend           |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
planebackend           |     raise ex.with_traceback(None)
planebackend           | django.db.utils.ProgrammingError: column "cover_image" of relation "users" does not exist
planebackend           | LINE 1: ...r", "email", "first_name", "last_name", "avatar", "cover_ima...
planebackend           |                                                              ^
planebackend exited with code 1
```

### Steps to reproduce

1. Git clone repo
2. build and docker-compose up -d (with docker-compose.yml)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by tyleraharrison** [comment]
Facing the same issue on the current `stage-release` branch and `develop`

**Comment by pablohashescobar** [comment]
Hi `develop`  and `stage-release` branch can be unstable it would be awesome if you could switch to `master` branch and rebuild the containers also you may have to delete all the container volumes as well before restarting.

**Comment by geniusshiun** [comment]
> 

Thank you for the suggestion. I've uesd master branch and it can work now.

**Comment by pablohashescobar** [comment]
Thanks for the update @geniusshiun closing this issue now.

**Comment by psychowood** [comment]
Not sure if I'm missing something, but creating a new container following the [official instructions](https://docs.plane.so/self-hosting) that checks-out from master but gives me exactly the same error...

[plane-log.txt](https://github.com/makeplane/plane/files/12217876/plane-log.txt)

**Comment by pablohashescobar** [comment]
Hi @psychowood you can switch to master branch and rerun the setup. It would be awesome if you could also delete the database volume.

**Comment by psychowood** [comment]
I'm AFK right now, I'll retry as soon as I can. Did you push something? The log I attached is from a clean clone+run from master.
