### ISSUE TITLE
[bug]: Jitsu hidden tracking?

### ISSUE THREAD

**Issue by leikoilja** [makeplane/plane#1717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Spotted this error on the frontend docker container logs:

```
2023-07-30T17:48:43.209397717Z [J-WARN] Id() is called before initialization
2023-07-30T17:48:43.644707874Z [J-ERROR] Failed to send data to /api/v1/s2s/event?token=: Failed to parse URL from /api/v1/s2s/event?token= [{"event_id":"","user":{"anonymous_id":"","id":"22dc7237-87b7-4278-8379-f32c5af03c7f","email":"xxx@gmail.com","first_name":"Ilja","last_name":"Leiko"},"ids":{},"utc_time":"2023-07-30T17:48:43.207000Z","local_tz_offset":0,"utm":{},"click_id":{},"api_key":"","src":"jitsu","event_type":"user_identify"},{"event_id":"","user":{"anonymous_id":"","id":"22dc7237-87b7-4278-8379-f32c5af03c7f","email":"xxx@gmail.com","first_name":"Ilja","last_name":"Leiko"},"ids":{},"utc_time":"2023-07-30T17:48:43.207000Z","local_tz_offset":0,"utm":{},"click_id":{},"api_key":"","src":"jitsu","event_type":"WORKSPACE_SCOPE_AND_DEMAND_ANALYTICS","workspaceSlug":"xxx"}] TypeError: Failed to parse URL from /api/v1/s2s/event?token=
2023-07-30T17:48:43.644920116Z     at Object.fetch (node:internal/deps/undici/undici:11576:11) {
2023-07-30T17:48:43.644989077Z   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
2023-07-30T17:48:43.645025389Z       at new NodeError (node:internal/errors:405:5)
2023-07-30T17:48:43.645058581Z       at new URL (node:internal/url:611:13)
2023-07-30T17:48:43.645088798Z       at new Request (node:internal/deps/undici/undici:7132:25)
2023-07-30T17:48:43.645120768Z       at fetch2 (node:internal/deps/undici/undici:10715:25)
2023-07-30T17:48:43.645150613Z       at Object.fetch (node:internal/deps/undici/undici:11574:18)
2023-07-30T17:48:43.645181026Z       at fetch (node:internal/process/pre_execution:229:25)
2023-07-30T17:48:43.645211639Z       at /app/node_modules/@jitsu/sdk-js/dist/npm/jitsu.cjs.js:772:46
2023-07-30T17:48:43.645244438Z       at step (/app/node_modules/@jitsu/sdk-js/dist/npm/jitsu.cjs.js:75:23)
2023-07-30T17:48:43.645275866Z       at Object.next (/app/node_modules/@jitsu/sdk-js/dist/npm/jitsu.cjs.js:56:53)
2023-07-30T17:48:43.645306842Z       at /app/node_modules/@jitsu/sdk-js/dist/npm/jitsu.cjs.js:49:71 {
2023-07-30T17:48:43.645335153Z     input: '/api/v1/s2s/event?token=',
2023-07-30T17:48:43.645365973Z     code: 'ERR_INVALID_URL'
2023-07-30T17:48:43.645409701Z   }
2023-07-30T17:48:43.645436608Z }
```
is there a way to opt out for that? if that's [jitsu](https://jitsu.com/) there seem to be no reference or way to configure it. The docker-compose yml refers to sentry for event collection

### Steps to reproduce

Pull latest docker images for plane

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
Hi @leikoilja, to disable Jitsu tracking, you can set the env variable `NEXT_PUBLIC_TRACK_EVENTS` to 0.

**Comment by vihar** [comment]
Hey @leikoilja, adding to @aaryan610, we don't collect any events or analytics from self-hosted instances. By default, the environment variable `NEXT_PUBLIC_TRACK_EVENTS` is set to `0`. The above errors appear to be caused by some validation issues, but our team will fix this.

**Comment by leikoilja** [comment]
Thanks for addressing it, @aaryan610 and @vihar. 
On my instance i already have `NEXT_PUBLIC_TRACK_EVENTS` set to `0`, so it must be not respected somewhere.

**Comment by srinivaspendem** [comment]
We have completely removed the Jitsu tracking. you will no longer encounter this issue.
