### ISSUE TITLE
[bug]: error creating project or workspace on v0.9-dev 

### ISSUE THREAD

**Issue by anibal-aguila** [makeplane/plane#1732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I create a new project or workspace I get **404 and 500 error**

Currently running behind traefik as reverse proxy and splitting well the web (port: 3000) and the /api (port: 3000)

<img width="1460" alt="image" src="https://github.com/makeplane/plane/assets/49025536/0626141f-9a8e-402a-8d49-20212ee99a59">

```
30.10.10.38:43806 - "GET /api/unsplash?page=1&per_page=20&query= HTTP/1.1" 404
30.10.10.38:49028 - "GET /api/workspaces/crosstask/members/ HTTP/1.1" 200
30.10.10.38:49014 - "GET /api/workspaces/crosstask/projects/?is_favorite=all HTTP/1.1" 200
30.10.10.38:49034 - "GET /api/unsplash?page=1&per_page=20&query= HTTP/1.1" 404
30.10.10.38:49034 - "POST /api/workspaces/crosstask/projects/ HTTP/1.1" 410
30.10.10.38:51374 - "GET /api/workspaces/crosstask/workspace-members/me/ HTTP/1.1" 200
30.10.10.38:51490 - "GET /api/unsplash?page=1&per_page=20&query= HTTP/1.1" 404
30.10.10.38:51408 - "GET /api/users/me/ HTTP/1.1" 200
30.10.10.38:51412 - "GET /api/workspaces/crosstask/projects/67f64c57-4c6e-40cb-a013-20e25c69f00b/members/ HTTP/1.1" 200
30.10.10.38:51372 - "GET /api/workspaces/crosstask/projects/?is_favorite=all HTTP/1.1" 200
30.10.10.38:51370 - "GET /api/users/me/workspaces/ HTTP/1.1" 500
30.10.10.38:51416 - "GET /api/workspaces/crosstask/users/notifications/unread/ HTTP/1.1" 200
30.10.10.38:51444 - "GET /api/workspaces/crosstask/projects/6d407240-4106-4508-a8fb-24521a50fe5e/members/ HTTP/1.1" 200
30.10.10.38:51426 - "GET /api/workspaces/crosstask/projects/af4b4c45-f0ca-4b49-978f-7072f88aa1f8/members/ HTTP/1.1" 200
30.10.10.38:51430 - "GET /api/workspaces/crosstask/projects/af27c853-1871-4839-bc13-9d2f3722262a/members/ HTTP/1.1" 200
30.10.10.38:51436 - "GET /api/workspaces/crosstask/members/ HTTP/1.1" 200
30.10.10.38:51458 - "GET /api/workspaces/crosstask/projects/2c4b5bdd-3a08-437d-a9ac-d6c7b1e8480d/members/ HTTP/1.1" 200
30.10.10.38:51452 - "GET /api/workspaces/crosstask/projects/bcd70ef1-2c8b-4323-84bc-38c7d0e0ad08/members/ HTTP/1.1" 200
30.10.10.38:51474 - "GET /api/workspaces/crosstask/users/notifications/?type=assigned&snoozed=false&archived=false HTTP/1.1" 500
```
Thanks in avance,

### Steps to reproduce

Add project Issue

### Browser

Google Chrome

### Version

Self-hosted

**Comment by anibal-aguila** [comment]
hello @rhea0110 thanks for mark this issue as a bug.

v0.10.0 allow to create the project but seems to be missing some parameters in django
<img width="1454" alt="Screenshot 2023-08-05 at 1 10 35 PM" src="https://github.com/makeplane/plane/assets/49025536/8272df57-2829-4cbd-b858-b9930d1008dc">


Regards,

```
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] ^
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess]
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] raise ex.with_traceback(None)
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] django.db.utils
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] .
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] ProgrammingError
d7ef7b7afa16 [2023-08-05 16:22:56,686: WARNING/MainProcess] :
d7ef7b7afa16 [2023-08-05 16:22:56,687: WARNING/MainProcess] relation "django_celery_beat_periodictask" does not exist
d7ef7b7afa16 LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce...
d7ef7b7afa16                                                              ^
d7ef7b7afa16 [2023-08-05 16:23:03,971: INFO/MainProcess] beat: Starting...
d7ef7b7afa16 [2023-08-05 16:23:04,178: INFO/MainProcess] DatabaseScheduler: Schedule changed.
7c770d42ff4b Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly
7c770d42ff4b Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly
70425a3bca6b 2023-08-05 11:07:40.552 UTC [17] LOG:  checkpoint starting: time
70425a3bca6b 2023-08-05 11:07:43.572 UTC [17] LOG:  checkpoint complete: wrote 31 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.008 s, sync=0.004 s, total=3.020 s; sync files=23, longest=0.002 s, average=0.001 s; distance=56 kB, estimate=1603 kB
^C
[bb@PRO-LOC-A02 plane]$
[bb@PRO-LOC-A02 plane]$ d7ef7b7afa16 [2023-08-05 16:40:33,224: ERROR/MainProcess] Database gave error: OperationalError('connection is bad: Name does not resolve')
d7ef7b7afa16 Traceback (most recent call last):
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
d7ef7b7afa16     self.connect()
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
d7ef7b7afa16     self.connection = self.get_new_connection(conn_params)
d7ef7b7afa16                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
d7ef7b7afa16     connection = self.Database.connect(**conn_params)
d7ef7b7afa16                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect
d7ef7b7afa16     raise ex.with_traceback(None)
d7ef7b7afa16 psycopg.OperationalError: connection is bad: Name does not resolve
d7ef7b7afa16
d7ef7b7afa16 The above exception was the direct cause of the following exception:
d7ef7b7afa16
d7ef7b7afa16 Traceback (most recent call last):
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django_celery_beat/schedulers.py", line 267, in schedule_changed
d7ef7b7afa16     last, ts = self._last_timestamp, self.Changes.last_change()
d7ef7b7afa16                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django_celery_beat/models.py", line 394, in last_change
d7ef7b7afa16     return cls.objects.get(ident=1).last_update
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
d7ef7b7afa16     return getattr(self.get_queryset(), name)(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
d7ef7b7afa16     num = len(clone)
d7ef7b7afa16           ^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
d7ef7b7afa16     self._fetch_all()
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
d7ef7b7afa16     self._result_cache = list(self._iterable_class(self))
d7ef7b7afa16                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
d7ef7b7afa16     results = compiler.execute_sql(
d7ef7b7afa16               ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
d7ef7b7afa16     cursor = self.connection.cursor()
d7ef7b7afa16              ^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
d7ef7b7afa16     return self._cursor()
d7ef7b7afa16            ^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
d7ef7b7afa16     self.ensure_connection()
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
d7ef7b7afa16     with self.wrap_database_errors:
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
d7ef7b7afa16     raise dj_exc_value.with_traceback(traceback) from exc_value
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
d7ef7b7afa16     self.connect()
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
d7ef7b7afa16     self.connection = self.get_new_connection(conn_params)
d7ef7b7afa16                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
d7ef7b7afa16     return func(*args, **kwargs)
d7ef7b7afa16            ^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
d7ef7b7afa16     connection = self.Database.connect(**conn_params)
d7ef7b7afa16                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
d7ef7b7afa16   File "/usr/local/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect
d7ef7b7afa16     raise ex.with_traceback(None)
```

**Comment by pablohashescobar** [comment]
Hi @anibal-aguila, can you check if you are facing the same issue in (0.10-dev) also.

**Comment by strongwer** [comment]
> Hi @anibal-aguila, can you check if you are facing the same issue in (0.10-dev) also.

update to 0.10-dev is the same, i got this error after i update from 0.9 to 0.13.2, then i tried 0.10. 

`File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
[2023-12-07 17:26:50,043: WARNING/MainProcess]
[2023-12-07 17:26:50,043: WARNING/MainProcess] raise ex.with_traceback(None)
[2023-12-07 17:26:50,043: WARNING/MainProcess] django.db.utils
[2023-12-07 17:26:50,043: WARNING/MainProcess] .
[2023-12-07 17:26:50,043: WARNING/MainProcess] ProgrammingError
[2023-12-07 17:26:50,043: WARNING/MainProcess] :
[2023-12-07 17:26:50,043: WARNING/MainProcess] relation "django_celery_beat_periodictask" does not exist
LINE 1: ...ango_celery_beat_periodictask"."description" FROM "django_ce.`

but if i change the git clone dir, e.g., plane -> plane2, then it's ok, but create a new db.

**Comment by vihar** [comment]
We've implemented significant changes to enhance the stability of the self-hosted version. To address this issue, please refer to the steps outlined in the migration documentation at https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x.
