### ISSUE TITLE
[bug]: Docker build step fills ram/swap and pegs cpu

### ISSUE THREAD

**Issue by MostHated** [makeplane/plane#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I went to run the `docker compose up` step it got to step 12/13 and seems to have completed compilation and began 'Collecting page data...', at which point the VM's memory quickly maxed out, followed by swap, while the CPU usage remained maxed out.

```Shell
 => [plane-web installer  6/13] COPY --from=builder /app/out/yarn.lock ./yarn.lock                                                                0.0s
 => [plane-web installer  7/13] RUN yarn install --network-timeout 500000                                                                        37.0s
 => [plane-web installer  8/13] COPY --from=builder /app/out/full/ .                                                                              0.2s
 => [plane-web installer  9/13] COPY turbo.json turbo.json                                                                                        0.0s
 => [plane-web installer 10/13] COPY replace-env-vars.sh /usr/local/bin/                                                                          0.0s
 => [plane-web installer 11/13] RUN chmod +x /usr/local/bin/replace-env-vars.sh                                                                   0.3s
 => [plane-web installer 12/13] RUN yarn turbo run build --filter=app                                                                           138.2s
 => => # t-hooks/exhaustive-deps
 => => # app:build:
 => => # app:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 => => # app:build: info  - Creating an optimized production build...
 => => # app:build: info  - Compiled successfully
 => => # app:build: info  - Collecting page data...
```
At this point I noticed that the time ticker display stopped counting, which was when I looked in proxmox and saw the VM locked up and the stats were all in 'uhho' mode. I then had to force a restart on the VM.

![](https://img.instance.id/EAMKU9FlR6sr/direct)

![](https://img.instance.id/OKqpNgBajcJ5/direct)

The VM is not particularly beastly, as I never expected to need it to be, but is allocated 6gb memory, 2gb swap, and 6 cores. I figured that should be plenty and this was some sort of bug?

I attempted this a few times now, and each time it gets to this step and produces the same result.

Thanks,
-MH

### Steps to reproduce

All I did was clone, ran the setup.sh step, then ran the instructed `docker compose up` command

### Browser

Other

### Version

Self-hosted

**Comment by pablohashescobar** [comment]
Hi @MostHated, we were unable to replicate this issue on our end can you check with the pre-built docker images using the `docker-compose-hub.yml`

**Comment by viseshrp** [comment]
@pablohashescobar I can confirm the same. This makes Plane unusable on ARM64 systems (for which prebuilt images do not exist). The yarn build stages are killing the CPU.

**Comment by joshbudde1994** [comment]
I can confirm this as well. Pulled from `master` today and have not been able to successfully build, between CPU load and time outs during `next build` for web (ultimately fails). I've included the output from page data collection onward. 

```
1338.6 web:build: info  - Collecting page data...
1427.7 web:build: warn  - Restarted collecting page data for /_error because it took more than 60 seconds
1427.8 web:build: warn  - See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.8 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1427.9 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.0 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.1 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.1 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.1 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1428.1 web:build: warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
1492.4 web:build:
1492.4 web:build: > Build error occurred
1492.5 web:build: Error: Collecting page data for [object Object] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
1492.5 web:build:     at onRestart (/app/node_modules/next/dist/build/index.js:593:35)
1492.5 web:build:     at Worker.isPageStatic (/app/node_modules/next/dist/lib/worker.js:48:40)
1492.5 web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1492.5 web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
1492.5 web:build:     at async /app/node_modules/next/dist/build/index.js:705:52
1492.5 web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
1492.5 web:build:     at async Promise.all (index 3)
1492.5 web:build:     at async /app/node_modules/next/dist/build/index.js:652:17
1492.5 web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
1492.5 web:build:     at async /app/node_modules/next/dist/build/index.js:617:170
1493.7 web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1493.9 web:build: error Command failed with exit code 1.
1494.2 web:build: ERROR: command finished with error: command (/app/web) yarn run build exited (1)
1494.2 web#build: command (/app/web) yarn run build exited (1)
1494.2
1494.2  Tasks:    0 successful, 1 total
1494.2 Cached:    0 cached, 1 total
1494.2   Time:    24m49.4s
1494.2 Failed:    web#build
1494.2
1494.2  ERROR  run failed: command  exited (1)
1494.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1494.8 error Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c yarn turbo run build --filter=web" did not complete successfully: exit code: 1
```

**Comment by vihar** [comment]
@MostHated, this issue has been fixed on our latest release. If it still persists, please re-open this issue. Docs for upgrade: https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x.
