### ISSUE TITLE
Web and Space container constantly restarts. web:dev: ERROR run failed: command exited (1)

### ISSUE THREAD

**Issue by halil-bugol** [makeplane/plane#3055]
I'm trying to set up a local development environment on Windows. When I up it with the docker-compose-local file. While another  containers are working correctly. Web and Space constantly restart and generate the same error

---
```
2023-12-10 04:28:21 yarn run v1.22.19
2023-12-10 04:28:21 $ turbo run dev --filter=web
2023-12-10 04:28:21 • Packages in scope: web
2023-12-10 04:28:21 • Running dev in 1 packages
2023-12-10 04:28:21 • Remote caching disabled
2023-12-10 04:28:26 web:dev: cache bypass, force executing 2205d20badd43121
2023-12-10 04:28:27 web:dev: $ turbo run develop
2023-12-10 04:28:27 web:dev: • Packages in scope: web
2023-12-10 04:28:27 web:dev: • Running develop in 1 packages
2023-12-10 04:28:27 web:dev: • Remote caching disabled
2023-12-10 04:28:31 web:dev: @plane/ui:build: cache miss, executing 18ee9f965948adcc
2023-12-10 04:28:31 web:dev: @plane/editor-types:build: cache miss, executing 881bd4af65ceffd6
2023-12-10 04:28:31 web:dev: @plane/editor-types:build: warning package.json: "dependencies" has dependency "eslint" with range "8.36.0" that collides with a dependency in "devDependencies" of the same name with version "^7.32.0"
2023-12-10 04:28:31 web:dev: @plane/ui:build: $ tsup src/index.ts --format esm,cjs --dts --external react --minify
2023-12-10 04:28:31 web:dev: @plane/editor-types:build: $ tsup --minify
2023-12-10 04:28:33 web:dev: @plane/ui:build: CLI Building entry: src/index.ts
2023-12-10 04:28:33 web:dev: @plane/ui:build: Error: Cannot find module 'tsconfig/react-library.json'
2023-12-10 04:28:33 web:dev: @plane/ui:build: Require stack:
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/node_modules/load-tsconfig/dist/index.cjs
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/node_modules/bundle-require/dist/index.cjs
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/chunk-O4DTJHFR.js
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/index.js
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/chunk-7E5MLYTU.js
2023-12-10 04:28:33 web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/cli-default.js
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at Function.resolve (node:internal/modules/helpers:188:19)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at resolveTsConfigFromExtends (/app/node_modules/load-tsconfig/dist/index.cjs:163:18)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at loadTsConfigInternal (/app/node_modules/load-tsconfig/dist/index.cjs:169:26)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at loadTsConfigInternal (/app/node_modules/load-tsconfig/dist/index.cjs:185:28)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at loadTsConfig (/app/node_modules/load-tsconfig/dist/index.cjs:209:35)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at normalizeOptions (/app/packages/ui/node_modules/tsup/dist/index.js:2027:48)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at async /app/packages/ui/node_modules/tsup/dist/index.js:2043:21
2023-12-10 04:28:33 web:dev: @plane/ui:build:     at async Promise.all (index 0)
2023-12-10 04:28:33 web:dev: @plane/ui:build: error Command failed with exit code 1.
2023-12-10 04:28:33 web:dev: @plane/ui:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-12-10 04:28:33 web:dev: @plane/ui:build: ERROR: command finished with error: command (/app/packages/ui) /tmp/yarn--1702171707176-0.1380671836666132/yarn run build exited (1)
2023-12-10 04:28:33 web:dev: @plane/ui#build: command (/app/packages/ui) /tmp/yarn--1702171707176-0.1380671836666132/yarn run build exited (1)
2023-12-10 04:28:33 web:dev: 
2023-12-10 04:28:33 web:dev:  Tasks:    0 successful, 2 total
2023-12-10 04:28:33 web:dev: Cached:    0 cached, 2 total
2023-12-10 04:28:33 web:dev:   Time:    6.14s 
2023-12-10 04:28:33 web:dev: Failed:    @plane/ui#build
2023-12-10 04:28:33 web:dev: 
2023-12-10 04:28:33 web:dev:  ERROR  run failed: command  exited (1)
2023-12-10 04:28:33 web:dev: error Command failed with exit code 1.
2023-12-10 04:28:33 web:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-12-10 04:28:33 
2023-12-10 04:28:33  Tasks:    0 successful, 1 total
2023-12-10 04:28:33 Cached:    0 cached, 1 total
2023-12-10 04:28:33   Time:    11.753s 
2023-12-10 04:28:33 Failed:    web#dev
2023-12-10 04:28:33 
2023-12-10 04:28:33 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---

**Comment by halil-bugol** [comment]
ping @mguptahub

**Comment by mguptahub** [comment]
Thinking how can it be different from mac. Still, let me look into it and get back to you.

**Comment by halil-bugol** [comment]
@mguptahub I see the same error on Mac.

**Comment by tonyeggers** [comment]
I had this same issue on Windows around the same time reported by @halil-bugol and have just been watching to see if it would be addressed (Docker Desktop v4.25.2 ).

yarn run v1.22.19
$ turbo run dev --filter=web
• Packages in scope: web
• Running dev in 1 packages
• Remote caching disabled
web:dev: cache bypass, force executing 7943b2fc22e1cd36
web:dev: $ turbo run develop
web:dev: • Packages in scope: web
web:dev: • Running develop in 1 packages
web:dev: • Remote caching disabled
web:dev: @plane/editor-types:build: cache miss, executing 1f5c49f0235219e5
web:dev: @plane/ui:build: cache miss, executing 4244fca6f0571e64
web:dev: @plane/editor-types:build: warning package.json: "dependencies" has dependency "eslint" with range "8.36.0" that collides with a dependency in "devDependencies" of the same name with version "^7.32.0"
web:dev: @plane/ui:build: $ tsup src/index.ts --format esm,cjs --dts --external react --minify
web:dev: @plane/editor-types:build: $ tsup --minify
web:dev: @plane/ui:build: CLI Building entry: src/index.ts
web:dev: @plane/ui:build: Error: Cannot find module 'tsconfig/react-library.json'
web:dev: @plane/ui:build: Require stack:
web:dev: @plane/ui:build: - /app/node_modules/load-tsconfig/dist/index.cjs
web:dev: @plane/ui:build: - /app/node_modules/bundle-require/dist/index.cjs
web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/chunk-O4DTJHFR.js
web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/index.js
web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/chunk-7E5MLYTU.js
web:dev: @plane/ui:build: - /app/packages/ui/node_modules/tsup/dist/cli-default.js
web:dev: @plane/ui:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
web:dev: @plane/ui:build:     at Function.resolve (node:internal/modules/helpers:188:19)
web:dev: @plane/ui:build:     at resolveTsConfigFromExtends (/app/node_modules/load-tsconfig/dist/index.cjs:163:18)
web:dev: @plane/ui:build:     at loadTsConfigInternal (/app/node_modules/load-tsconfig/dist/index.cjs:169:26)
web:dev: @plane/ui:build:     at loadTsConfigInternal (/app/node_modules/load-tsconfig/dist/index.cjs:185:28)
web:dev: @plane/ui:build:     at loadTsConfig (/app/node_modules/load-tsconfig/dist/index.cjs:209:35)
web:dev: @plane/ui:build:     at normalizeOptions (/app/packages/ui/node_modules/tsup/dist/index.js:2027:48)
web:dev: @plane/ui:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web:dev: @plane/ui:build:     at async /app/packages/ui/node_modules/tsup/dist/index.js:2043:21
web:dev: @plane/ui:build:     at async Promise.all (index 0)
web:dev: @plane/ui:build: error Command failed with exit code 1.
web:dev: @plane/ui:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web:dev: @plane/ui:build: ERROR: command finished with error: command (/app/packages/ui) /tmp/yarn--1702481821530-0.7728859002152173/yarn run build exited (1)
web:dev: @plane/ui#build: command (/app/packages/ui) /tmp/yarn--1702481821530-0.7728859002152173/yarn run build exited (1)
web:dev: 
web:dev:  Tasks:    0 successful, 2 total
web:dev: Cached:    0 cached, 2 total
web:dev:   Time:    7.421s 
web:dev: Failed:    @plane/ui#build
web:dev: 
web:dev:  ERROR  run failed: command  exited (1)
web:dev: error Command failed with exit code 1.
web:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    22.837s 
Failed:    web#dev

**Comment by Arvin-Zi** [comment]
@mguptahub  im having the same problem on mac for these two container as well

**Comment by mguptahub** [comment]
We have identified the issue and a PR has been created to fix it. Wait for it to get approved and merged.

**Comment by halil-bugol** [comment]
I tested it and it worked.

**Comment by Arvin-Zi** [comment]
@halil-bugol im still having the same problem, what have you done to fix it ?

**Comment by Arvin-Zi** [comment]
@mguptahub i can not see ant PR for this issue, is the solution approved
?

**Comment by halil-bugol** [comment]
@Arvin-Zi Which branch are you using?

**Comment by tonyeggers** [comment]
@halil-bugol, @mguptahub, This appears to be resolved for me for the web-1/plane-web container when using the new preview branch recently updated.  However, I'm still getting restarts with:

api-1/plain-api: exec ./bin/takeoff.local: no such file or directory
best-worker-1/plane-beat-worker: relation "django_celery_beat_periodictask" does not exist
proxy-1/plane-proxy: exec /docker-entrypoint.sh: no such file or directory

**Comment by Arvin-Zi** [comment]
@halil-bugol  im using the preview branch, are you running the web on port 80 localhost right?

**Comment by shubhamf22labs** [comment]
@mguptahub  can you share PR link for this issue?

**Comment by tonyeggers-neurored** [comment]
Hey @shubhamf22labs @Arvin-Zi ... I have the web container working now with the master branch.  Make sure you prune the old docker builds (docker buildx prune) before running 'docker compose -f docker-compose-local.yml up -d" so you properly rebuild everything.

**Comment by tonyeggers** [comment]
Hey @shubhamf22labs @Arvin-Zi ... I have the web container working now with the master branch. Make sure you prune the old docker builds (docker buildx prune) before running 'docker compose -f docker-compose-local.yml up -d" so you properly rebuild everything.

**Comment by Arvin-Zi** [comment]
@tonyeggers  thanks very much for you help its working now, but im getting this error when im running it "Your Plane instance isn't ready yet
Ask your Instance Admin to complete set-up first." what should i do?

**Comment by tonyeggers** [comment]
> @tonyeggers thanks very much for you help its working now, but im getting this error when im running it "Your Plane instance isn't ready yet Ask your Instance Admin to complete set-up first." what should i do?

Cool.  Make sure you start out with http://x.x.x.x/god-mode to get everything going. 

https://github.com/makeplane/plane/issues/3173#issuecomment-1860438796
