### ISSUE TITLE
[bug]: Migration issues upgrading to v0.14.x

### ISSUE THREAD

**Issue by samkpr** [makeplane/plane#3371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrading to v0.14.x

Getting this error 

Tried migration script 

`root@ip-172-31-95-103:/home/ubuntu/plane-selfhost# docker logs --tail 50 --follow --timestamps fcb8165dc005
2024-01-15T05:17:50.453081847Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
2024-01-15T05:17:50.453213608Z     operation.database_forwards(
2024-01-15T05:17:50.453224907Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
2024-01-15T05:17:50.453364495Z     self.code(from_state.apps, schema_editor)
2024-01-15T05:17:50.453376264Z   File "/code/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py", line 124, in workspace_member_properties
2024-01-15T05:17:50.453575402Z     obj.default_props["properties"]["start_date"] = True
2024-01-15T05:17:50.453587932Z     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2024-01-15T05:17:50.453592996Z KeyError: 'properties'
2024-01-15T05:17:50.922038025Z   Applying db.0041_cycle_sort_order_issuecomment_access_and_more...2024-01-15T05:17:55.830513138Z Waiting for database...
2024-01-15T05:17:55.830554321Z Database available!
2024-01-15T05:18:00.398661469Z Operations to perform:
2024-01-15T05:18:00.398705447Z   Apply all migrations: auth, authtoken, contenttypes, db, django_celery_beat, license, sessions, token_blacklist
2024-01-15T05:18:00.608932478Z Running migrations:
2024-01-15T05:18:03.437620838Z Traceback (most recent call last):
2024-01-15T05:18:03.437665173Z   File "/code/manage.py", line 17, in <module>
2024-01-15T05:18:03.437940231Z     execute_from_command_line(sys.argv)
2024-01-15T05:18:03.438074835Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024-01-15T05:18:03.438443018Z     utility.execute()
2024-01-15T05:18:03.438553360Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2024-01-15T05:18:03.438859627Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-01-15T05:18:03.439004964Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2024-01-15T05:18:03.439339670Z     self.execute(*args, **cmd_options)
2024-01-15T05:18:03.439466063Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2024-01-15T05:18:03.439812275Z     output = self.handle(*args, **options)
2024-01-15T05:18:03.442467048Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.442529725Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
2024-01-15T05:18:03.442882880Z     res = handle_func(*args, **kwargs)
2024-01-15T05:18:03.444942835Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.445019565Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
2024-01-15T05:18:03.445336629Z     post_migrate_state = executor.migrate(
2024-01-15T05:18:03.446556045Z                          ^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.446576758Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
2024-01-15T05:18:03.446861831Z     state = self._migrate_all_forwards(
2024-01-15T05:18:03.446874505Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.446879561Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
2024-01-15T05:18:03.447076364Z     state = self.apply_migration(
2024-01-15T05:18:03.447089060Z             ^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.447093966Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
2024-01-15T05:18:03.447365716Z     state = migration.apply(state, schema_editor)
2024-01-15T05:18:03.447377982Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:03.447383093Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
2024-01-15T05:18:03.447520720Z     operation.database_forwards(
2024-01-15T05:18:03.447532557Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
2024-01-15T05:18:03.447624313Z     self.code(from_state.apps, schema_editor)
2024-01-15T05:18:03.447634968Z   File "/code/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py", line 124, in workspace_member_properties
2024-01-15T05:18:03.447823839Z     obj.default_props["properties"]["start_date"] = True
2024-01-15T05:18:03.447834621Z     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2024-01-15T05:18:03.447936324Z KeyError: 'properties'
2024-01-15T05:18:03.932807738Z   Applying db.0041_cycle_sort_order_issuecomment_access_and_more...2024-01-15T05:18:08.495827892Z Waiting for database...
2024-01-15T05:18:08.495887077Z Database available!
2024-01-15T05:18:13.065376126Z Operations to perform:
2024-01-15T05:18:13.065428064Z   Apply all migrations: auth, authtoken, contenttypes, db, django_celery_beat, license, sessions, token_blacklist
2024-01-15T05:18:13.258694103Z Running migrations:
2024-01-15T05:18:16.035427964Z Traceback (most recent call last):
2024-01-15T05:18:16.035476937Z   File "/code/manage.py", line 17, in <module>
2024-01-15T05:18:16.036207244Z     execute_from_command_line(sys.argv)
2024-01-15T05:18:16.036222842Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024-01-15T05:18:16.036228623Z     utility.execute()
2024-01-15T05:18:16.036246190Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2024-01-15T05:18:16.036251561Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-01-15T05:18:16.036256246Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2024-01-15T05:18:16.037552310Z     self.execute(*args, **cmd_options)
2024-01-15T05:18:16.037568472Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2024-01-15T05:18:16.037575613Z     output = self.handle(*args, **options)
2024-01-15T05:18:16.037579062Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.037583576Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
2024-01-15T05:18:16.037588368Z     res = handle_func(*args, **kwargs)
2024-01-15T05:18:16.037592772Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.037597284Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
2024-01-15T05:18:16.037601886Z     post_migrate_state = executor.migrate(
2024-01-15T05:18:16.037606317Z                          ^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.037610782Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
2024-01-15T05:18:16.037630603Z     state = self._migrate_all_forwards(
2024-01-15T05:18:16.037637142Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.037641615Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
2024-01-15T05:18:16.037646221Z     state = self.apply_migration(
2024-01-15T05:18:16.037650608Z             ^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.037655154Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
2024-01-15T05:18:16.039007015Z     state = migration.apply(state, schema_editor)
2024-01-15T05:18:16.039023057Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-15T05:18:16.039028164Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
2024-01-15T05:18:16.039033255Z     operation.database_forwards(
2024-01-15T05:18:16.039037754Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
2024-01-15T05:18:16.039042550Z     self.code(from_state.apps, schema_editor)
2024-01-15T05:18:16.039047211Z   File "/code/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py", line 124, in workspace_member_properties
2024-01-15T05:18:16.039055088Z     obj.default_props["properties"]["start_date"] = True
2024-01-15T05:18:16.039060039Z     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^`

Migration script ran successfully 

`root@ip-172-31-95-103:/home/ubuntu/plane-selfhost# ./migrate.sh

******************************************************************

This script is solely for the migration purpose only. 
This is a 1 time migration of volume data from v0.13.2 => v0.14.x

Assumption: 
1. Postgres data volume name ends with _pgdata
2. Minio data volume name ends with _uploads
3. Redis data volume name ends with _redisdata

Any changes to this script can break the migration. 

Before you proceed, make sure you run the below command
to know the docker volumes

docker volume ls -q | grep -i "_pgdata"
docker volume ls -q | grep -i "_uploads"
docker volume ls -q | grep -i "_redisdata"

*******************************************************

Given below list of REDIS volumes, identify the prefix of source and destination volumes leaving "_redisdata" 
---------------------
plane-app_redisdata
plane_redisdata

Provide the Source Volume Prefix : plane
Provide the Destination Volume Prefix : plane-app

Prefix Provided 
  Source : plane
  Destination : plane-app
---------------------------------------
MIGRATING pgdata FROM plane_pgdata => plane-app_pgdata

MIGRATING redisdata FROM plane_redisdata => plane-app_redisdata

MIGRATING uploads FROM plane_uploads => plane-app_uploads`

### Steps to reproduce

Using Ubuntu 23.10, install self-hosted plane as given in [https://docs.plane.so/self-hosting/docker-compose .](https://docs.plane.so/self-hosting/docker-compose)

<img width="1207" alt="image" src="https://github.com/makeplane/plane/assets/101115929/07edcb79-f5b0-44b4-82b1-68a503515dc0">

### Browser

Google Chrome

### Version

Self-hosted

**Comment by samkpr** [comment]
Any update on this one??

**Comment by samkpr** [comment]
It's been a 2 weeks since I raised this issue. Couldn't use plane anymore.

**Comment by pablohashescobar** [comment]
@samkpr sorry we missed this.  But just to confirm are you facing this issue when updating from 0.13.2 to 0.14 or are you updating directly to 0.14. It is recommended to first update to 0.13.2 then to 0.14.

**Comment by samkpr** [comment]
How to upgrade to 0.13.2

**Comment by mguptahub** [comment]
> How to upgrade to 0.13.2

What is the current version from which you are trying to upgrade to v0.13.2 ?

**Comment by pushya22** [comment]
Hi @samkpr please re-open if you are still facing the issue.
