### ISSUE TITLE
[bug]: Sort by Due Date Column not working as expected 

### ISSUE THREAD

**Issue by melgo-tb** [makeplane/plane#3579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Sorting by  Due Date Column for both ascending and descending does not seem to sort the items based on the values of the due date column.

### Steps to reproduce

1) Create issues with multiple different due dates on different days
2) Sort by old->new or new->old
3) console has this error 

```
Uncaught (in promise) Error: View id is required
    at updateFilters (_app-d68d80d63f3d0cf9.js:211:102560)
    at e0 (_app-d68d80d63f3d0cf9.js:154:17920)
    at updateFilters (_app-d68d80d63f3d0cf9.js:154:17471)
    at 8650-805176f336e4552b.js:7:96650
    at u (8650-805176f336e4552b.js:7:145244)
    at onClick (8650-805176f336e4552b.js:7:146035)
    at onClick (_app-d68d80d63f3d0cf9.js:234:157108)
    at Object.eU (framework-c5aaf663751111c6.js:9:14910)
    at eH (framework-c5aaf663751111c6.js:9:15064)
    at framework-c5aaf663751111c6.js:9:33370
    at re (framework-c5aaf663751111c6.js:9:33469)
    at rn (framework-c5aaf663751111c6.js:9:33883)
    at framework-c5aaf663751111c6.js:9:39339
    at oN (framework-c5aaf663751111c6.js:9:96306)
    at eF (framework-c5aaf663751111c6.js:9:14048)
    at ro (framework-c5aaf663751111c6.js:9:35174)
    at nU (framework-c5aaf663751111c6.js:9:20843)
    at nD (framework-c5aaf663751111c6.js:9:20627)
    at HTMLDivElement.r (_app-d68d80d63f3d0cf9.js:166:2891)
updateFilters @ _app-d68d80d63f3d0cf9.js:211
e0 @ _app-d68d80d63f3d0cf9.js:154
updateFilters @ _app-d68d80d63f3d0cf9.js:154
(anonymous) @ 8650-805176f336e4552b.js:7
u @ 8650-805176f336e4552b.js:7
onClick @ 8650-805176f336e4552b.js:7
onClick @ _app-d68d80d63f3d0cf9.js:234
eU @ framework-c5aaf663751111c6.js:9
eH @ framework-c5aaf663751111c6.js:9
(anonymous) @ framework-c5aaf663751111c6.js:9
re @ framework-c5aaf663751111c6.js:9
rn @ framework-c5aaf663751111c6.js:9
(anonymous) @ framework-c5aaf663751111c6.js:9
oN @ framework-c5aaf663751111c6.js:9
eF @ framework-c5aaf663751111c6.js:9
ro @ framework-c5aaf663751111c6.js:9
nU @ framework-c5aaf663751111c6.js:9
nD @ framework-c5aaf663751111c6.js:9
r @ _app-d68d80d63f3d0cf9.js:166
```

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hello @melgo-tb, the reported issue has been resolved. Thank you for your input. If you encounter any further issues, please let us know.
