### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by dmikushin** [makeplane/plane#3618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've upgraded 0.13-dev to 0.15-dev and getting error 500 on any API request due to InvalidToken. Symptoms are identical to #3583 , but the cause appears to be different.

I use the same `SECRET_KEY` value as before and confirmed it is correctly propagated into containers as an environment variable.

```
{"error":"Unhandled exception: InvalidToken

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cryptography/fernet.py", line 134, in _verify_signature
    h.verify(data[-32:])
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/plane/app/views/base.py", line 212, in handle_exception
    response = super().handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/plane/app/views/config.py", line 37, in get
    ) = get_configuration_value(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/plane/license/utils/instance_value.py", line 26, in get_configuration_value
    decrypt_data(item.get("value"))
  File "/code/plane/license/utils/encryption.py", line 27, in decrypt_data
    decrypted_data = cipher_suite.decrypt(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/fernet.py", line 91, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/fernet.py", line 152, in _decrypt_data
    self._verify_signature(data)
  File "/usr/local/lib/python3.11/site-packages/cryptography/fernet.py", line 136, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
"}
```

### Steps to reproduce

1. Add traceback to exception handling in apiserver, rebuild and start the docker containers
2. Run a sample request, e.g. `curl https://example.com/api/configs/`
3. Get 500 error with the formatted error description presented above

### Browser

Google Chrome

### Version

Self-hosted

**Comment by dmikushin** [comment]
I'm now really pissed off by what I found.

**Caution: this message contains rude and offensive language, but the situation deserves it.**

I have a problem due to "encryption", which is supposed to be applied to the API tokens (but apparently is not):

In `apiserver/plane/license/management/commands/configure_instance.py`:

```python
             {
                 "key": "GITHUB_CLIENT_SECRET",
                 "value": os.environ.get("GITHUB_CLIENT_SECRET"),
                 "category": "GITHUB",
                 "is_encrypted": True,
             },
```

What the hell does this mean? Am I supposed to have some encryption on top of the client secret token? Why do I have to learn about this from the code, after tweaking it all around for multiple hours to add the completely missing diagnostics?

However, one half of this config is actually marked deprecated, e.g. `EMAIL_HOST`, `OPENAI_API_KEY` and so on.

Long story short, I get my old good Plane working after I cut this shit out:

```patch
diff --git a/apiserver/plane/license/utils/instance_value.py b/apiserver/plane/license/utils/instance_value.py
index bc4fd5d21..69297d996 100644
--- a/apiserver/plane/license/utils/instance_value.py
+++ b/apiserver/plane/license/utils/instance_value.py
@@ -21,13 +21,7 @@ def get_configuration_value(keys):
         for key in keys:
             for item in instance_configuration:
                 if key.get("key") == item.get("key"):
-                    if item.get("is_encrypted", False):
-                        environment_list.append(
-                            decrypt_data(item.get("value"))
-                        )
-                    else:
-                        environment_list.append(item.get("value"))
-
+                    environment_list.append(item.get("value"))
                     break
             else:
                 environment_list.append(key.get("default"))
```

Guys, your left hand is not knowing what the right hand is doing. Care about adding some comments? Is documentation forbidden to exist in your region? This is not professional. Please stop trashing the good project. This coding style is really really ugly and misleading. I'll try to send my patches.

**Comment by pablohashescobar** [comment]
@dmikushin, the `is_encrypted` flag is set to true for all the environment variables that are saved into db which require encryption. We will add necessary comments wherever required. 

They are marked as **deprecated** from setting it in the `.env` file as they can be set on god mode  and the god mode settings take precedence over the `.env` settings.
