### ISSUE TITLE
[bug]: Mail not sending, no errors even without proper SMTP configuration

### ISSUE THREAD

**Issue by Reloecc** [makeplane/plane#3980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am currently debugging our self-hosted Plane app, using setup.sh to start it. We utilize Docker. Plane is currently version 0.16, although I upgraded from 0.14.2 hoping to resolve the issue, but it didn't help.

I'm encountering a problem with sending emails from within the Plane app, such as member invitations and password resets. I'm confident that my credentials are correct, and the SMTP server is operational. Other services on the server can successfully use the SMTP server. I even accessed Plane's Docker containers via bash to ensure my credentials are properly set as environment variables.

The real issue here is that I have no idea how to debug this behavior. I've set debug=1 in .env, but there are no relevant reports in the Docker logs. The core of the debugging process lies in the fact that I don't see any errors even if I unset the relevant environment variables or enter nonsense values. Plane still notifies me with "Invitations sent successfully."

Is it normal for the Plane not to check for SMTP errors and not present them to the frontend or log them?

In addition to user, host, etc., my settings currently look like this, but I've also tried ports 465 and 25 (as my SMTP server supports them) without TLS and with SSL. However, I was not successful in resolving this issue.

Please help.

```
EMAIL_PORT=587
EMAIL_USE_TLS=1
EMAIL_USE_SSL=0
```

### Steps to reproduce

1) setup no env variables for EMAIL_HOST in .env
2) send invitation e-mail

### Environment

Production

### Browser

Other

### Version

Self-hosted

**Comment by ToolReaz** [comment]
Hello,

I have the exact same problem as you. I tested on the same version and I'm also self-hosting with Docker.
I tested my SMTP configuration with other tools and even a basic script using nodemailer and it works fine.

**Comment by Reloecc** [comment]
> Hello,
> 
> I have the exact same problem as you. I tested on the same version and I'm also self-hosting with Docker. I tested my SMTP configuration with other tools and even a basic script using nodemailer and it works fine.

I have no update on this issue. Our plane is not very usable right now because of this. I can add we had smtp working on 0.14.2 before, with smtp server on the same server as plane were running on. We migrated smtp server and I was not able to connect plane to it. Without ANY error messages.. it's not possible to know what's wrong :/.

**Comment by ToolReaz** [comment]
I found [in this issue's comment](https://github.com/makeplane/plane/issues/3311#issuecomment-2002077152) someone giving a command to test email. I entered in api's container shell to try but the command failed:

`6d162933608f:/code$ python manage.py test_email "<email>"
Unknown command: 'test_email'. Did you mean sendtestemail?`

So i tried the recommended command and got the following error:

`6d162933608f:/code$ python manage.py sendtestemail "<email>"
Traceback (most recent call last):
  File "/code/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/sendtestemail.py", line 35, in handle
    send_mail(
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available`

I continue to investigate...

**Comment by mguptahub** [comment]
@Reloecc @ToolReaz 

Hope you guys have followed the instructions available on [docs](https://docs.plane.so/self-hosting/govern/communication) to setup smtp configuration

**Comment by mguptahub** [comment]
@Reloecc 

All the SMTP configuration have been moved to GOD MODE. 

After 1st time setup of application / db initalization, SMTP configuration from ENV will get saved in DB for further use. Later on user can modify the SMTP settings from God Mode screens. This means  that SMTP env changes after 1st setup , will not be picked by application.

**Comment by Reloecc** [comment]
> After 1st time setup of application / db initalization, SMTP configuration from ENV will get saved in DB for further use.

Well.. that explains a thing. Thank you. My bad then on this point.

**Comment by muffintime77** [comment]
I would like to add that I am seeing the same problem. a solution cannot be found. variables are configured via the interface

**Comment by lordjoo** [comment]
still having the same error and when trying 
```
 python manage.py test_email
```

I'm getting this 
```
Trying to send test email...
Error: Email could not be delivered due to [Errno -2] Name does not resolve
```

even my SMTP is working fine and have tested it with other tools

**Comment by MarkNLD** [comment]
Has anyone identified the cause of the SMTP configuration issues? 
Some of my SMTP accounts are working correctly, while others are failing (different ESP's).

**Comment by brdelphus** [comment]
I found that Django's environment variable loading happens at import time. In containerized environments, environment variables weren't being picked up by the Django settings module during initialization.

  Solution:
  To force Django to re-read environment variables at pod startup by:
  1. Injecting email configuration after the pod starts
  2. Reading environment variables fresh (using os.environ.get())
  3. Ensuring these settings take precedence over any defaults
 API -> apply to local.py from .email_verride import *
WORKER -> /code/plane/settings/common.py

PS: kubernetes helm chart version

**Comment by sriramveeraghanta** [comment]
Closing this one out — the debuggability gap that started this thread has been addressed since 0.16.

**On the original confusion (env vars):** as @mguptahub noted above, SMTP settings are read from `.env` only on first initialization and are then persisted to the database. After that, God Mode is the source of truth and `.env` changes are ignored. Docs: https://docs.plane.so/self-hosting/govern/communication

**On the actual bug — silent failures:** there are now two ways to get a real error out of Plane instead of guessing:

1. **God Mode → Email → "Send test email".** It reports the specific SMTP failure — invalid credentials, could not connect, from-address invalid, recipients refused, timeout, or network error — instead of a generic success.
2. **From the API container:** `python manage.py test_email you@example.com`, which prints the underlying exception.

Actual invite and password-reset sends run in a Celery worker, and delivery failures are logged there with a full traceback. If a test email succeeds but invites don't arrive, check the **worker** container's logs, not `api` — that's where those errors land.

One thing that hasn't changed and is intentional: the invite endpoint returns success as soon as the email is queued, since delivery happens asynchronously. "Invitation sent" means "queued," not "delivered." Use the test-email check above to validate the configuration itself.

To everyone still hitting failures on newer versions — @muffintime77, @lordjoo, @MarkNLD, @brdelphus — those look like distinct problems rather than the one reported here:

- `[Errno -2] Name does not resolve` / `[Errno 99] Address not available` are the container failing to resolve or reach the SMTP host, which is a networking/DNS problem outside Plane.
- @brdelphus's Helm-chart env-loading behavior is specific to the Kubernetes deployment and is worth its own issue against the chart.

Please open a new issue with your version, deployment method, and the output of the God Mode test email or `test_email` command, and we'll pick it up from there. Thanks for the detailed reports on this one.
