### ISSUE TITLE
[bug]: PlaneOne and SSO with Keycloak: error 500

### ISSUE THREAD

**Issue by olivierlambert** [makeplane/plane#4599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Configure Keycloak + PlaneOne, as soon I have a validate login with keycloak, I'm then redirected to Plane and it's giving me:
```
Server Error (500)
```

Not that much. I don't know exactly where to look for more logs.

### Steps to reproduce

1. Configure and Enable SSO
2. Login

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.20.0 (PlaneOne)

**Comment by pablohashescobar** [comment]
Hi @olivierlambert, can you check the logs using the `monitor` command on cli. Also have you configured the sso using the steps mentioned below [here](https://docs.plane.so/plane-one/self-host/authentication/custom-sso).

**Comment by olivierlambert** [comment]
Hi @pablohashescobar !

1. Yes, I tried to stick to the official doc as possible, even if for Keycloak, things are a bit different
2. Sure, but I don't think what container to monitor exactly?

**Comment by pablohashescobar** [comment]
You can `monitor` the api container.

**Comment by olivierlambert** [comment]
Okay so I used `docker logs` for the API container and found the following error:

```
WARNING 2024-05-26 19:15:23,197 log 25 139714014464824 Unauthorized: /api/users/me/
<hidden_URL>:38794 - "GET /api/users/me/ HTTP/1.1" 401
<hidden_URL>:38786 - "GET /auth/oidc/ HTTP/1.1" 302
ERROR 2024-05-26 19:15:29,984 log 26 139714001574712 Internal Server Error: /auth/oidc/callback/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/plane/authentication/views/app/oidc.py", line 82, in get
    user = provider.authenticate()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/plane/authentication/adapter/oauth.py", line 48, in authenticate
    self.set_token_data()
  File "/code/plane/authentication/provider/oauth/oidc.py", line 98, in set_token_data
    token_response = self.get_user_token(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/code/plane/authentication/adapter/oauth.py", line 57, in get_user_token
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://xxx.xxxx.tld/realms/xxxx-internal/protocol/openid-connect/token
<hidden_URL>:38798 - "GET /auth/oidc/callback/?state=xxx&session_state=xxx&iss=https%3A%2F%2Fxxx.xxxx.tld%2Frealms%2Fxxxx-internal&code=<long_UUID_string> HTTP/1.1" 500

```

**Comment by pablohashescobar** [comment]
@olivierlambert, looks like an error was returned from the IdP on fetching the user token. Can you check if the configured credentials are correct.

**Comment by olivierlambert** [comment]
If they weren't, I couldn't even go further than Keycloak login page. So this message comes when I'm redirected from Keycloak to Plane, and that's precisely when I'm landing on the Error 500 page.

**Comment by olivierlambert** [comment]
It works!! :partying_face: The issue was a bad client secret copy/paste (hidden by default in the UI, so I missed it). Sorry for the noise, thank you for your assistance :+1:
