### ISSUE TITLE
[bug]: Internal server Error - when I try to upload an image

### ISSUE THREAD

**Issue by MirandaAnaconda** [makeplane/plane#5320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to upload an image, I get this Error
![plane-image-error](https://github.com/user-attachments/assets/49749993-4e55-4b27-a25f-5cbcaa743e25)
the APi Log says
api-1  | ERROR 2024-08-05 08:29:53,974 exception_logger 3808 140637369649976 Could not connect to the endpoint URL: "http://plane-minio:9000/uploads/d0a00516-6b9f-4fe0-a9b2-03c0d94ad751/25405e2d777c429abf701db03e707806-IMG20240720165441_cut_small2.jpg"
api-1  | ERROR 2024-08-05 08:29:53,994 log 3808 140637377039160 Internal Server Error: /api/workspaces/team-XXXXX/file-assets/
api-1  | 172.18.0.12:43994 - "POST /api/workspaces/team-XXXXX/file-assets/ HTTP/1.1" 500

What's the problem?
I can't understand.

### Steps to reproduce

1. I go to my site an Login as user
2. I create workspace
3. I create one project
4. when I try to upload a logo for my workspace 
5. I found the API Logs

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

latest

**Comment by pablohashescobar** [comment]
@MirandaAnaconda, can you share the logs for the api container.

**Comment by MirandaAnaconda** [comment]
I found this in API Log from plane setup
cut
api-1  | Waiting for database...
api-1  | Database available!
api-1  | No migrations Pending. Starting processes ...
api-1  | Instance already registered
api-1  | ENABLE_SIGNUP configuration already exists
api-1  | ENABLE_EMAIL_PASSWORD configuration already exists
api-1  | ENABLE_MAGIC_LINK_LOGIN configuration already exists
api-1  | GOOGLE_CLIENT_ID configuration already exists
api-1  | GOOGLE_CLIENT_SECRET configuration already exists
api-1  | GITHUB_CLIENT_ID configuration already exists
api-1  | GITHUB_CLIENT_SECRET configuration already exists
api-1  | GITLAB_HOST configuration already exists
api-1  | GITLAB_CLIENT_ID configuration already exists
api-1  | GITLAB_CLIENT_SECRET configuration already exists
api-1  | EMAIL_HOST configuration already exists
api-1  | EMAIL_HOST_USER configuration already exists
api-1  | EMAIL_HOST_PASSWORD configuration already exists
api-1  | EMAIL_PORT configuration already exists
api-1  | EMAIL_FROM configuration already exists
api-1  | EMAIL_USE_TLS configuration already exists
api-1  | EMAIL_USE_SSL configuration already exists
api-1  | OPENAI_API_KEY configuration already exists
api-1  | GPT_ENGINE configuration already exists
api-1  | UNSPLASH_ACCESS_KEY configuration already exists
api-1  | IS_GOOGLE_ENABLED configuration already exists
api-1  | IS_GITHUB_ENABLED configuration already exists
api-1  | IS_GITLAB_ENABLED configuration already exists
api-1  | Checking bucket...
api-1  | An error occurred: Could not connect to the endpoint URL: "http://plane-minio:9000/uploads"
api-1  | Cache Cleared
api-1  | [2024-08-13 10:10:47 +0000] [1] [INFO] Starting gunicorn 22.0.0
api-1  | [2024-08-13 10:10:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
api-1  | [2024-08-13 10:10:47 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
api-1  | [2024-08-13 10:10:47 +0000] [25] [INFO] Booting worker with pid: 25
api-1  | [2024-08-13 10:10:48 +0000] [25] [INFO] Started server process [25]
api-1  | [2024-08-13 10:10:48 +0000] [25] [INFO] Waiting for application startup.
api-1  | [2024-08-13 10:10:48 +0000] [25] [INFO] ASGI 'lifespan' protocol appears unsupported.
api-1  | [2024-08-13 10:10:48 +0000] [25] [INFO] Application startup complete.
api-1  | GET - /api/instances/ of Queries: 3
api-1  | 172.18.0.4:42934 - "GET /api/instances/ HTTP/1.1" 200
api-1  | GET - /api/users/me/ of Queries: 2
api-1  | 172.18.0.4:42962 - "GET /api/users/me/ HTTP/1.1" 200
api-1  | GET - /api/users/me/profile/ of Queries: 3
api-1  | 172.18.0.4:42976 - "GET /api/users/me/profile/ HTTP/1.1" 200
api-1  | GET - /api/users/me/settings/ of Queries: 6
api-1  | 172.18.0.4:42978 - "GET /api/users/me/settings/ HTTP/1.1" 200
api-1  | GET - /api/users/me/workspaces/ of Queries: 4
api-1  | 172.18.0.4:42982 - "GET /api/users/me/workspaces/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/users/notifications/unread/ of Queries: 3
api-1  | 172.18.0.4:42990 - "GET /api/workspaces/test-isabel/users/notifications/unread/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/workspace-members/me/ of Queries: 3
api-1  | 172.18.0.4:43002 - "GET /api/workspaces/test-isabel/workspace-members/me/ HTTP/1.1" 200
api-1  | GET - /api/users/me/workspaces/test-isabel/project-roles/ of Queries: 4
api-1  | 172.18.0.4:43030 - "GET /api/users/me/workspaces/test-isabel/project-roles/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/members/ of Queries: 5
api-1  | GET - /api/workspaces/test-isabel/dashboard/?dashboard_type=home of Queries: 4
api-1  | 172.18.0.4:43044 - "GET /api/workspaces/test-isabel/dashboard/?dashboard_type=home HTTP/1.1" 200
api-1  | 172.18.0.4:43014 - "GET /api/workspaces/test-isabel/members/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/projects/ of Queries: 5
api-1  | 172.18.0.4:43006 - "GET /api/workspaces/test-isabel/projects/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?cursor=8:0:0&per_page=8&search=&widget_key=recent_collaborators of Queries: 6
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=issues_by_priority of Queries: 3
api-1  | 172.18.0.4:43054 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?cursor=8:0:0&per_page=8&search=&widget_key=recent_collaborators HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=issues_by_state_groups of Queries: 3
api-1  | 172.18.0.4:43090 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=issues_by_priority HTTP/1.1" 200
api-1  | 172.18.0.4:43080 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=issues_by_state_groups HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=overview_stats of Queries: 6
api-1  | 172.18.0.4:43058 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=overview_stats HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=recent_projects of Queries: 4
api-1  | 172.18.0.4:43108 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=recent_projects HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=assigned_issues&issue_type=pending&expand=issue_relation of Queries: 4
api-1  | 172.18.0.4:43066 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=assigned_issues&issue_type=pending&expand=issue_relation HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=recent_activity of Queries: 3
api-1  | 172.18.0.4:43106 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=recent_activity HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=created_issues&issue_type=pending of Queries: 7
api-1  | 172.18.0.4:43070 - "GET /api/workspaces/test-isabel/dashboard/5216c9e1-8b1a-4f19-b50a-c3e670ca84de/?widget_key=created_issues&issue_type=pending HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/users/notifications/unread/ of Queries: 3
api-1  | 172.18.0.4:39636 - "GET /api/workspaces/test-isabel/users/notifications/unread/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/users/notifications/unread/ of Queries: 3
api-1  | 172.18.0.4:48774 - "GET /api/workspaces/test-isabel/users/notifications/unread/ HTTP/1.1" 200
api-1  | ERROR 2024-08-13 10:14:02,551 exception_logger 25 140577393023800 Could not connect to the endpoint URL: "http://plane-minio:9000/uploads/1bace13e-4ba0-4ff0-a3f2-a638188fce4a/f419181a72d5460193aec0c118abca03-Admine.jpg"
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
api-1  |     sock = connection.create_connection(
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
api-1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
api-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  | socket.gaierror: [Errno -2] Name does not resolve
api-1  | 
api-1  | The above exception was the direct cause of the following exception:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
api-1  |     urllib_response = conn.urlopen(
api-1  |                       ^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
api-1  |     retries = retries.increment(
api-1  |               ^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 449, in increment
api-1  |     raise reraise(type(error), error, _stacktrace)
api-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
api-1  |     raise value
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
api-1  |     response = self._make_request(
api-1  |                ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
api-1  |     conn.request(
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 96, in request
api-1  |     rval = super().request(method, url, body, headers, *args, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 398, in request
api-1  |     self.endheaders()
api-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1277, in endheaders
api-1  |     self._send_output(message_body, encode_chunked=encode_chunked)
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 123, in _send_output
api-1  |     self.send(msg)
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 223, in send
api-1  |     return super().send(str)
api-1  |            ^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/http/client.py", line 975, in send
api-1  |     self.connect()
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 236, in connect
api-1  |     self.sock = self._new_conn()
api-1  |                 ^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
api-1  |     raise NameResolutionError(self.host, self, e) from e
api-1  | urllib3.exceptions.NameResolutionError: <botocore.awsrequest.AWSHTTPConnection object at 0x7fdab99549d0>: Failed to resolve 'plane-minio' ([Errno -2] Name does not resolve)
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/code/plane/app/views/base.py", line 194, in handle_exception
api-1  |     response = super().handle_exception(exc)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/code/plane/app/views/asset/base.py", line 45, in post
api-1  |     serializer.save(workspace_id=workspace.id)
api-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 208, in save
api-1  |     self.instance = self.create(validated_data)
api-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 989, in create
api-1  |     instance = ModelClass._default_manager.create(**validated_data)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
api-1  |     obj.save(force_insert=True, using=self.db)
api-1  |   File "/code/plane/db/models/base.py", line 40, in save
api-1  |     super(BaseModel, self).save(*args, **kwargs)
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
api-1  |     self.save_base(
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
api-1  |     updated = self._save_table(
api-1  |               ^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
api-1  |     results = self._do_insert(
api-1  |               ^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
api-1  |     return manager._insert(
api-1  |            ^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
api-1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
api-1  |     for sql, params in self.as_sql():
api-1  |                        ^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
api-1  |     value_rows = [
api-1  |                  ^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
api-1  |     [
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
api-1  |     self.prepare_value(field, self.pre_save_val(field, obj))
api-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
api-1  |     return field.pre_save(obj, add=True)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 317, in pre_save
api-1  |     file.save(file.name, file.file, save=False)
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 93, in save
api-1  |     self.name = self.storage.save(name, content, max_length=self.field.max_length)
api-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/base.py", line 37, in save
api-1  |     name = self.get_available_name(name, max_length=max_length)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/storages/backends/s3.py", line 662, in get_available_name
api-1  |     return super().get_available_name(name, max_length)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/base.py", line 77, in get_available_name
api-1  |     while self.exists(name) or (max_length and len(name) > max_length):
api-1  |           ^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/storages/backends/s3.py", line 514, in exists
api-1  |     self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
api-1  |     return self._make_api_call(operation_name, kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1001, in _make_api_call
api-1  |     http, parsed_response = self._make_request(
api-1  |                             ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1027, in _make_request
api-1  |     return self._endpoint.make_request(operation_model, request_dict)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
api-1  |     return self._send_request(request_dict, operation_model)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 202, in _send_request
api-1  |     while self._needs_retry(
api-1  |           ^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 354, in _needs_retry
api-1  |     responses = self._event_emitter.emit(
api-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
api-1  |     return self._emitter.emit(aliased_event_name, **kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
api-1  |     return self._emit(event_name, kwargs)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
api-1  |     response = handler(**kwargs)
api-1  |                ^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
api-1  |     if self._checker(**checker_kwargs):
api-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
api-1  |     should_retry = self._should_retry(
api-1  |                    ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
api-1  |     return self._checker(attempt_number, response, caught_exception)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
api-1  |     checker_response = checker(
api-1  |                        ^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
api-1  |     return self._check_caught_exception(
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
api-1  |     raise caught_exception
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
api-1  |     http_response = self._send(request)
api-1  |                     ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
api-1  |     return self.http_session.send(request)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 493, in send
api-1  |     raise EndpointConnectionError(endpoint_url=request.url, error=e)
api-1  | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://plane-minio:9000/uploads/1bace13e-4ba0-4ff0-a3f2-a638188fce4a/f419181a72d5460193aec0c118abca03-Admine.jpg"
api-1  | 
api-1  | POST - /api/workspaces/test-isabel/file-assets/ of Queries: 4
api-1  | ERROR 2024-08-13 10:14:02,591 log 25 140577378437944 Internal Server Error: /api/workspaces/test-isabel/file-assets/
api-1  | 172.18.0.4:48776 - "POST /api/workspaces/test-isabel/file-assets/ HTTP/1.1" 500
api-1  | GET - /api/workspaces/test-isabel/users/notifications/unread/ of Queries: 3
api-1  | 172.18.0.4:58788 - "GET /api/workspaces/test-isabel/users/notifications/unread/ HTTP/1.1" 200
api-1  | GET - /api/workspaces/test-isabel/users/notifications/unread/ of Queries: 3
api-1  | 172.18.0.4:35178 - "GET /api/workspaces/test-isabel/users/notifications/unread/ HTTP/1.1" 200

**Comment by pushya22** [comment]
Hi @MirandaAnaconda Feel free to re-open the issue if you are still facing the issue after updating to out latest version
