### ISSUE TITLE
[bug]: (monitor) invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by axelrindle** [makeplane/plane#5722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d1725]

goroutine 89 [running]:
github.com/makeplane/plane-ee/monitor/lib/healthcheck.TcpHealthCheckMethod({0xd30b80?, 0xc000318230?}, {0xc00007c150, 0xc00007c1c0, {0xc00002c06c, 0x8}, 0xc000558200, 0x5, 0x3, 0x12a05f200, ...})
        /app/lib/healthcheck/healthcheck_methods.go:66 +0xe5
created by github.com/makeplane/plane-ee/monitor/lib/healthcheck.(*HealthCheckHandler).ExecuteHealthCheckWithRetries.func1 in goroutine 88
        /app/lib/healthcheck/healthcheck.go:189 +0x425
```

### Steps to reproduce

🤷‍♂️

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v1.3.1

**Comment by akshat5302** [comment]
The cause of this issue is the port number actually. To fix this issue you can try two options, 

Either you can free up your port 80 and try the express setup once again or
You can go to the advanced mode, and switch the port to something else, where the default port is 80, like 8080.
